version: "2"
run:
  go: "1.24"
linters:
  default: none
  enable:
    - contextcheck
    - errname
    #- govet
    - ineffassign
    #- revive
    - sqlclosecheck
    #- staticcheck
    - unused
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
