linters:
  disable-all: true
  enable:
    - dogsled
    - exportloopref
    - govet
    - gofmt
    - gocritic
    - godox
    - misspell
    - staticcheck
    - unconvert
#  presets:
#    - bugs
#    - unused
#    - style
#    - format
#    - performance
#    - complexity
