linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - exportloopref
    - govet
    - gofmt
    - goimports
    - gocritic
    - godox
    - misspell
    - staticcheck
    - stylecheck
    - unconvert
