language: go
go:
- "1.13.1"
os: linux
services: docker
before_install:
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
script:
  - make docker-lint
  - make docker-test 
