version: "3.4"

networks:
  cb:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      - "POSTGRES_USER=btokens"
      - "POSTGRES_PASSWORD=password"
    networks:
      - cb
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local:1.12.0
    networks: 
      - cb
    ports: 
      - "8000:8000"
  challenge-bypass:
    container_name: challenge-bypass
    image: challenge-bypass-builder 
    restart: always
    build:
      context: .
      target: go_builder 
    ports:
      - "2416:2416"
    environment:
      - "SENTRY_DSN"
      - "DATABASE_URL=postgres://btokens:password@postgres/btokens?sslmode=disable"
      - "DYNAMODB_ENDPOINT=http://dynamodb:8000"
    depends_on:
      - postgres
      - dynamodb
    networks:
      - cb

