version: "3.4"

networks:
  cb:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      - "POSTGRES_USER=btokens"
      - "POSTGRES_PASSWORD=password"
    networks:
      - cb
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local:1.12.20
  challenge-bypass:
    container_name: challenge-bypass
    image: challenge-bypass-builder 
    restart: always
    build:
      context: .
      target: go_builder 
    ports:
      - "2416:2416"
    environment:
      - "SENTRY_DSN"
      - "DATABASE_URL=postgres://btokens:password@postgres/btokens?sslmode=disable"
    depends_on:
      - postgres
    networks:
      - cb

