version: "3.4"

networks:
  cb:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./.prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - challenge-bypass:challenge-bypass
    depends_on:
      - challenge-bypass
    networks:
      - cb
    restart: always

  postgres:
    container_name: postgres
    image: postgres:11
    environment:
      - "POSTGRES_USER=btokens"
      - "POSTGRES_PASSWORD=password"
    networks:
      - cb
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local:1.12.0
    networks: 
      - cb
    ports: 
      - "8000:8000"
  challenge-bypass:
    container_name: challenge-bypass
    image: challenge-bypass-builder 
    restart: always
    build:
      context: .
      target: go_builder 
    ports:
      - "2416:2416"
    environment:
      - KAFKA_BROKERS=kafka:19092
      - KAFKA_SSL_CA_LOCATION=/etc/kafka/secrets/snakeoil-ca-1.crt
      - KAFKA_SSL_CERTIFICATE_LOCATION=/etc/kafka/secrets/consumer-ca1-signed.pem
      - KAFKA_SSL_KEY_LOCATION=/etc/kafka/secrets/consumer.client.key
      - "PPROF_ENABLE"
      - "PPROF_PORT"
      - "SENTRY_DSN"
      - "DATABASE_URL=postgres://btokens:password@postgres/btokens?sslmode=disable"
      - "DYNAMODB_ENDPOINT=http://dynamodb:8000"
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-west-2
    depends_on:
      - postgres
      - dynamodb
    networks:
      - cb
    volumes:
      - ./test/secrets:/etc/kafka/secrets

  zookeeper:
    container_name: grant-zookeeper
    image: confluentinc/cp-zookeeper:7.1.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - cb

  kafka:
    container_name: grant-kafka
    image: confluentinc/cp-kafka:7.1.1
    ports:
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "SSL://kafka:19092,SSL2://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL,SSL2:SSL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker1.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: broker1_keystore_creds
      KAFKA_SSL_KEY_CREDENTIALS: broker1_sslkey_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker1.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker1_truststore_creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      KAFKA_SSL_CLIENT_AUTH: requested
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_RETENTION_MS: 10000
    volumes:
      - ./test/secrets:/etc/kafka/secrets
    depends_on:
      - zookeeper
    networks:
      - cb