services:
  cbp:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      localstack:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://testuser:testpassword@postgres:5432/testdb?sslmode=disable
      - VPC_KAFKA_BROKERS=kafka:9092
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - ENV=test
      - REDEEM_CONSUMER_TOPIC=test.consumer.redeem
      - REDEEM_PRODUCER_TOPIC=test.producer.redeem
      - SIGN_CONSUMER_TOPIC=test.consumer.sign
      - SIGN_PRODUCER_TOPIC=test.producer.sign
      - CONSUMER_GROUP=integration-service
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    ports:
      - "2416:2416"
      - "9090:9090"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 2s
      retries: 10

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 5s
      timeout: 2s
      retries: 10

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=test.consumer.redeem:1:1,test.producer.redeem:1:1,test.consumer.sign:1:1,test.producer.sign:1:1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      # Reduce memory usage for testing
      - KAFKA_HEAP_OPTS=-Xmx256M -Xms128M
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 10

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
    healthcheck:
      test: ["CMD", "sh", "-c", "awslocal dynamodb list-tables --region us-east-1 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 15

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    profiles:
      - test
    depends_on:
      cbp:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://testuser:testpassword@postgres:5432/testdb?sslmode=disable
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - ENV=test
      - TEST_SHOULD_WRITE_REDEEM_REQUESTS_HERE=test.consumer.redeem
      - TEST_SHOULD_READ_REDEEM_REQUESTS_HERE=test.producer.redeem
      - TEST_SHOULD_WRITE_SIGNING_REQUESTS_HERE=test.consumer.sign
      - TEST_SHOULD_READ_SIGNING_REQUESTS_HERE=test.producer.sign
      - CONSUMER_GROUP=test
    command: ["go", "test", "-tags", "integration", "./integration-tests", "-v", "-count=1"]
