name: tests
on:
  pull_request:
    branches:
      - master
      - prod
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: run tests
        run: make docker-test
