name: tests
on:
  pull_request:
    branches:
      - master
      - prod
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: run lint
        run: make lint
      - name: run tests
        run: make docker-test
