on:
  push:
    branches:
      - "master"
      - "ads-prod"
      - "ads-stage"

name: CBP Deployments
jobs:
  push:
    name: Invoke Challenge By Pass Docker Build Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.GDBP_AWS_IAM_ROLE_ARN }}
        aws-region: us-west-2
    - name: Challenge Bypass Server Deployments
      uses: brave-intl/general-docker-build-pipeline-action@v1.0.9
