name: Integration Tests

on:
  pull_request:
    branches:
      - master
      - prod
    types:
      - opened
      - synchronize
      - reopened

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run integration tests
        run: make integration-test

      - name: Cleanup
        if: always()
        run: make integration-test-clean
